#!/usr/bin/env bash
# ==============================================================================
# deploy/fetch-oci-vault-secrets.sh
# Pulls secrets from OCI Vault and writes /etc/forsic/.env
# Run once before first deployment, then re-run whenever secrets rotate.
#
# Prerequisites on VM:
#   - OCI CLI installed and configured (oci setup config)
#   - OCI Vault created with the secrets listed below
#   - Run as root or with sudo
#
# Usage:
#   sudo bash deploy/fetch-oci-vault-secrets.sh
# ==============================================================================
set -euo pipefail

ENV_DIR="/etc/forsic"
ENV_FILE="${ENV_DIR}/.env"

echo "======================================================"
echo " FORSIC — Fetching secrets from OCI Vault"
echo "======================================================"

# ---- Create secure directory for env file ----
mkdir -p "${ENV_DIR}"
chmod 700 "${ENV_DIR}"

# ---- Check if OCI CLI is available ----
if ! command -v oci &>/dev/null; then
  echo "[WARN] OCI CLI not found. Falling back to manual secret entry."
  MANUAL_MODE=true
else
  MANUAL_MODE=false
fi

# ---- Helper: fetch a secret by name from OCI Vault ----
# Usage: fetch_secret <VAULT_OCID> <SECRET_NAME>
fetch_secret() {
  local vault_ocid="$1"
  local secret_name="$2"
  local secret_ocid

  secret_ocid=$(oci vault secret list \
    --compartment-id "${OCI_COMPARTMENT_OCID}" \
    --vault-id "${vault_ocid}" \
    --query "data[?\"secret-name\"=='${secret_name}'].id | [0]" \
    --raw-output 2>/dev/null)

  if [[ -z "${secret_ocid}" || "${secret_ocid}" == "null" ]]; then
    echo "[ERROR] Secret '${secret_name}' not found in OCI Vault." >&2
    return 1
  fi

  oci secrets secret-bundle get \
    --secret-id "${secret_ocid}" \
    --query 'data."secret-bundle-content".content' \
    --raw-output | base64 --decode
}

# ---- Write .env file ----
write_env() {
  local postgres_password="$1"
  local redis_password="$2"
  local minio_password="$3"
  local jwt_secret="$4"
  local kms_key="$5"
  local pki_password="$6"

  cat > "${ENV_FILE}" <<EOF
# =======================================================
# FORSIC Production Secrets — Auto-generated by fetch-oci-vault-secrets.sh
# DO NOT EDIT MANUALLY. Re-run the script to refresh.
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =======================================================

SPRING_PROFILES_ACTIVE=prod

POSTGRES_DB=sih190_db
POSTGRES_USER=sih190_user
POSTGRES_PASSWORD=${postgres_password}

SPRING_DATA_REDIS_HOST=redis
SPRING_DATA_REDIS_PORT=6379
REDIS_PASSWORD=${redis_password}

MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${minio_password}
S3_BUCKET_NAME=sih190-evidence-vault
S3_QUARANTINE_BUCKET_NAME=sih190-quarantine-vault

CLAMAV_ENABLED=true
CLAMAV_FAIL_CLOSED=true
CLAMAV_HOST=clamav
CLAMAV_PORT=3310

ELASTICSEARCH_URL=http://elasticsearch:9200
ELASTICSEARCH_ENABLED=true

JWT_SECRET=${jwt_secret}
JWT_AUDIENCE=sih190-api
KMS_MASTER_KEY=${kms_key}
PKI_KEYSTORE_PASSWORD=${pki_password}

SERVER_PORT=8080
FRONTEND_PORT=3000
EOF

  chmod 600 "${ENV_FILE}"
  echo "[OK] Secrets written to ${ENV_FILE} (mode 600)"
}

# ---- OCI Vault mode ----
if [[ "${MANUAL_MODE}" == "false" ]]; then
  echo ""
  echo "Enter your OCI details:"
  read -rp "  OCI Compartment OCID: " OCI_COMPARTMENT_OCID
  read -rp "  OCI Vault OCID:        " OCI_VAULT_OCID
  export OCI_COMPARTMENT_OCID

  echo ""
  echo "[*] Fetching secrets from OCI Vault..."

  POSTGRES_PASSWORD=$(fetch_secret "${OCI_VAULT_OCID}" "FORSIC_POSTGRES_PASSWORD")
  REDIS_PASSWORD=$(fetch_secret "${OCI_VAULT_OCID}" "FORSIC_REDIS_PASSWORD")
  MINIO_PASSWORD=$(fetch_secret "${OCI_VAULT_OCID}" "FORSIC_MINIO_PASSWORD")
  JWT_SECRET=$(fetch_secret "${OCI_VAULT_OCID}" "FORSIC_JWT_SECRET")
  KMS_MASTER_KEY=$(fetch_secret "${OCI_VAULT_OCID}" "FORSIC_KMS_MASTER_KEY")
  PKI_KEYSTORE_PASSWORD=$(fetch_secret "${OCI_VAULT_OCID}" "FORSIC_PKI_KEYSTORE_PASSWORD")

  write_env "${POSTGRES_PASSWORD}" "${REDIS_PASSWORD}" "${MINIO_PASSWORD}" \
            "${JWT_SECRET}" "${KMS_MASTER_KEY}" "${PKI_KEYSTORE_PASSWORD}"

# ---- Manual fallback mode ----
else
  echo ""
  echo "[MANUAL MODE] Enter your production secrets (input is hidden):"
  read -rsp "  POSTGRES_PASSWORD:    " POSTGRES_PASSWORD; echo
  read -rsp "  REDIS_PASSWORD:       " REDIS_PASSWORD; echo
  read -rsp "  MINIO_ROOT_PASSWORD:  " MINIO_PASSWORD; echo
  read -rsp "  JWT_SECRET:           " JWT_SECRET; echo
  read -rsp "  KMS_MASTER_KEY:       " KMS_MASTER_KEY; echo
  read -rsp "  PKI_KEYSTORE_PASSWORD:" PKI_KEYSTORE_PASSWORD; echo

  write_env "${POSTGRES_PASSWORD}" "${REDIS_PASSWORD}" "${MINIO_PASSWORD}" \
            "${JWT_SECRET}" "${KMS_MASTER_KEY}" "${PKI_KEYSTORE_PASSWORD}"
fi

echo ""
echo "======================================================"
echo " Secrets fetched successfully. Ready to deploy."
echo " Run:  sudo bash deploy/deploy.sh"
echo "======================================================"
