spring:
  datasource:
    url: jdbc:h2:file:./storage_vault/db/sih190_dev;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  flyway:
    enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false

app:
  s3:
    local-fs-fallback: true
    local-storage-path: ./target/dev-storage-vault
  clamav:
    enabled: false
